from utils import emotes

data = {
    "admin_source": f"{emotes.Meh} No, **<val1>**, but you're the author of the original source code.",
    "admin_yes": f"{emotes.Allow} Yes, **<val1>**, you are the owner.",
    "admin_no": f"{emotes.Deny} No, **<val1>**, back off!",
    "input_too_long": "You attempted to make the command display more than 2,000 characters, didn't you?\n"
                      "Congratulations, you broke it. Now go find something more interesting to do.",
    "error_occurred": f"{emotes.Deny} There has been an error, try again later... I'll spam Regaus about this.\n`<val1>`",
    "command_cooldown": f"{emotes.Deny} This command is on cooldown... try again in <val1>",
    "max_concurrency": f"{emotes.Deny} This command has reached its max concurrency. Try again later.",
    "server_locked": f"{emotes.Deny} This command has been disabled in this server.",
    "channel_locked": f"{emotes.Deny} Use the bot commands channel for this.",
    "time_command": f"**<val3>**, the current time is:\nSenko Lair: **<val2>**\nLocal time: **<val1>**\nUTC: **<val4>**",
    "settings_template": "Here's the settings template for you.\nUpload with `<val1>settings upload`",
    "settings_template_detailed": "Here's the settings template for you.\nUpload with `<val1>settings upload`\nFor leveling, [USER] will show user's "
                                  "name, and [MENTION] will @mention them",
    "settings_current": "Current settings for **<val1>**\nUse `<val2>settings template` for the template.",
    "settings_upload_no1": f"{emotes.Deny} This must be a JSON file.",
    "settings_upload_no2": f"{emotes.Deny} There was an error getting the file.",
    "settings_upload_no3": f"{emotes.Deny} There must be exactly one JSON file.",
    "settings_upload_no4": f"{emotes.Deny} Error loading file:\n`<val1>`",
    "settings_upload_yes": f"{emotes.Allow} Settings have been updated.\nDB status: <val1>",
    "premium": "No. Just no.",
    "birthday_today": "Happy birthday <val1>, have a nice birthday and enjoy your role today 🎂🎉",
    "birthday_self": f"I have birthday on **13th May**, thank you for asking. {emotes.AlexHeart}",
    "birthday_none": "**<val1>** has not saved his/her birthday :(",
    "birthday_you": "**You** have birthday on **<val1>**",
    "birthday_other": "**<val1>** has birthday on **<val2>**",
    "birthday_already_set": "Your birthday is already to **<val1>**\nTo change this, please contact the owner of the bot.",
    "birthday_no": "You need to enter a valid date with the command. `[ DD/MM ]`",
    "birthday_confirm": "Alright **<val1>**, do you confirm that your birth date is **<val2>**?\nType `<val3>` to confirm this choice\n"
                        "(NOTE: To change birthday later, you must send valid birthday to the owner)",
    "birthday_no2": "~~<val1>~~\n\nWelp, you decided not to respond...",
    "birthday_set": "Done, your birth date is now saved in my database at **<val1>** 🎂",
    "avatar": "Avatar to **<val1>**\n<val2>",
    "roles_in_server": "Roles in **<val1>**",
    "user_joined_at": "**<val1>** joined **<val2>** on <val3>",
    "username": "Username",
    "nickname": "Nickname",
    "user_id": "User ID",
    "created_at": "Created at",
    "joined_at": "Joined at",
    "current_status": "Current Status",
    "current_activity": "Current Activity",
    "no": "No",
    "roles": "Roles",
    "about_user": "ℹ About **<val1>**",
    "emoji_desc": "Name: <val1>\nID: <val2>\nAnimated: <val3>\nServer: <val4>\nCreated: <val5>\n[Copy Link](<val6>)",
    "only_in_senko_lair": f"{emotes.Deny} This command is only available in Senko Lair.",
    "server_name": "Server name",
    "server_id": "Server ID",
    "owner": "Owner",
    "members": "Member count",
    "bots": "Bot count",
    "region": "Region",
    "ban_count": "Ban count",
    "access_denied": "Access denied",
    "channels": "Channel count",
    "channels2": "<val1> text channels\n<val2> categories\n<val3> voice channels",
    "about_server": "About **<val1>**",
    "server_icon": "**<val1>**'s server icon\n<val2>",
    "bots_in_server": "Bots in **<val1>**: ```ini\n<val2>```",
    "status_of_users": "Status of members of **<val1>**",
    "total_members": "Total members",
    "status": "Status",
    "status2": "<val1> Online: <val2> - <val3>%, of which:\nMobile: <val4> | Desktop: <val5> | Web: <val6>\n\n<val7> Idle: <val8> - <val9>%, of which:"
               "\nMobile: <val10> | Desktop: <val11> | Web: <val12>\n\n<val13> Dungeons and Dragons: <val14> - <val15>%, of which:\n"
               "Mobile: <val16> | Desktop: <val17> | Web: <val18>\n\n<val19> Offline: <val20> - <val21>%",
    "activities": "Activities",
    "activities2": "Out of <val1> people online:\n<val2> Playing a game: <val3> - <val4>%\n<val5> Playing Custom Status: <val6> - <val7>%\n"
                   "<val8> Streaming: <val9> - <val10>%\n<val11> Listening: <val12> - <val13>%\n<val14> Doing nothing: <val15> - <val16>%",
    "default_prefixes": "Default prefixes",
    "custom_prefixes": "Custom prefixes",
    "server_prefixes": "Bot prefixes in **<val1>**",
    "bots_money": "Bots can't have any money, cuz they're cheaters. I get my money from Regaus, don't worry.",
    "no_money": "Doesn't appear like <val1> has any money at all...",
    "balance": "**<val1>** has **<val2><val3>** in **<val4>**",
    "donate_negative": f"{emotes.Deny} Nice try, <val1>.",
    "donate_self": f"{emotes.Deny} <val1>, giving money to yourself? Greedy.",
    "no_money2": f"{emotes.Deny} It doesn't seem like you even have any money to begin with...",
    "no_money3": f"{emotes.Deny} <val1>, it doesn't seem like you have enough money to do that...",
    "donate_yes": f"{emotes.Allow} <val1> just gave <val2><val3> to <val4>. {emotes.AlexHeart}",
    "money_self": "Enough",
    "donated_self": "Never bothered counting",
    "more_than_you": "More than you",
    "more_than_you2": "More than you",
    "profile": "**<val1>'s** profile in **<val2>**",
    "money": "Money",
    "donated": "Donated",
    "shop_empty": "It doesn't seem like this server has anything to sell...",
    "shop": "**<val1>** Shop",
    "shop_item": "<@&<val2>>: <val1><val3>\n",
    "buy_role_no": f"{emotes.Deny} <val1>, The role <val2> is not available for purchase...",
    "buy_role_confirm": "<val1>, Are you sure you want to buy the role <val2> for <val3><val4>? Type `yes` to confirm.",
    "buy_role_no2": "~~<val1>~~\n\nI'm taking the lack of response as a no...",
    "buy_role_no3": f"{emotes.Deny} <val1>, you already have the role <val2>...",
    "buy_role_no4": f"{emotes.Deny} <val1>, you don't have enough money to buy the role <val2>... (<val3>/<val4><val5>)",
    "buy_role_no5": f"{emotes.Deny} <val1>, it doesn't seem like you even have any money to begin with...",
    "buy_role_forbidden": f"{emotes.Deny} I don't have the permissions required to give you the role - contact the admins...",
    "buy_role_success": f"{emotes.Allow} <val1> successfully bought role <val2> for <val3><val4>.",
    "none": "None",
    "boosts": "Server boosts",
    "boosts2": "<val1> Boost(s) - Level <val2>\n<val3> total booster(s)",
    "emotes": "Emotes",
    "emotes2": "<val3>/<val1> non-animated\n<val2>/<val1> animated\n<val4> total",
    "shard_id": "Shard ID",
    "verification_level": "Verification level",
    "low": "Low",
    "medium": "Medium",
    "high": "High",
    "extreme": "Extreme",
    "level_reward_failed": f"{emotes.Deny} <val1> should have got a level reward, but I do not have sufficient permissions to do so.",
    "rewards_none": "Doesn't seem like this server has leveling rewards",
    "rewards_title": "Rewards for having no life in <val1>",
    "rewards_reward": "Level <val1>: <@&<val2>>\n",
    "rank_place_unknown": "Unknown",
    "rank_place_num": "#<val1>",
    "rank_level": "Level <val1>",
    "rank_rank": "Rank <val1>",
    "rank_xp": "<val1>/<val2> XP\nProgress: <val3>%",
    "rank_xp_self": "9,999,999,999,999 XP",
    "rank_user": "**<val1>**'s rank in **<val2>**",
    "rank_self": "\nThat's my card! Did you think I'd play fair?",
    "nl_no_data": "It doesn't seem like I have any data saved for you right now...",
    "max_level": "The max level is <val1>.",
    "xl_index_error": "An error occurred while trying to get data for level <val1>. Make sure it is below the max level (<val2>).",
    "xp_level_base": "<val1>: To reach level **<val2>** you will need **<val3> XP**",
    "xp_level_extra": "\nXP left to reach level: **<val1>**\nEstimated time left: **<val2> to <val3>**",
    "next_level_data": "**<val1>**: You currently have **<val2>/<val3>** XP.\nYou need **<val4>** more to reach level **<val5>** "
                       "(Progress: **<val6>%**).\nEstimated talking time: **<val7> to <val8>**",
    "levels_no_data": "I have no data at all for this server... Weird",
    "levels_lb": "Top users in <val1> - Sorted by XP\nYour place: <val2>\nShowing places <val4> to <val5> of <val6>\n<val3>```",
    "levels_global": "Top users globally - Sorted by XP\nYour place: <val1>\nShowing places <val3> to <val4> of <val5>\n<val2>```",
    "experience": "Experience",
    "level": "Level",
    "higher_than_yours": "Higher than yours",
    "rank_progress": "Progress to next level",
    "rank_progress2": "<val1>% - <val2> XP to level up",
    "xp_per_message": "XP per message",
    "global_rank": "**<val1>** has **<val2> XP** globally and is **<val3>** on the leaderboard.",
    "love_locked": f"{emotes.Deny} Imagine annoying Regaus so much he locks the command for you, <val1>.",
    "bad_locked": "Says the bad one, <val1>...",
    "server_banner": "**<val1>**'s server banner\n<val2>",
    "server_splash": "**<val1>**'s server invite background\n<val2>",
    "server_banner_none": "**<val1>** has no banner",
    "server_splash_none": "**<val1>** has no invite background",
    "time_since": "Current time: **<val1>**\nSpecified time: **<val2>**\nResult: **<val3>**",
    "time_since_error": "There was an error:\n<val1>",
    "luas": "Data available for <val1>:\n<val2>\n<val3>",
    "current_weather": "Current weather",
    "temperature": "Temperature",
    "pressure": "Pressure",
    "humidity": "Humidity",
    "wind_speed": "Wind speed",
    "cloud_cover": "Cloud cover",
    "sunrise": "Sunrise",
    "sunset": "Sunset",
    "weather_error": f"{emotes.Deny} Could not get weather for <val1>:\n<val2>: <val3>",
    "weather_output": "<val1> Weather in **<val2>, <val3>**",
    "weather_output2": "Local time: **<val1>**",
    "iq": "**<val1>'s** IQ is **<val2>**",
    "hot_calc": "**<val1>** is **<val2>%** hot <val3>",
    "love_calc": "Love level between <val1> and <val2> is **<val3>**%",
    "bots_love": "Bots can't feel love towards normal users...",
    "already_taken": "<val1>, I am already taken...",
    "lc_same": "I don't think that's how it works...",
    "baby_rate": "The chance of <val1> and <val2> having a baby is **<val3>**%",
    "baby_rate_bot": "Bots weren't made to have babies...",
    "baby_rate_self": "I wasn't programmed for that, <val1>...",
    "rate": "I'd rate <val1> a **<val2>/100**",
    "message_del_error": "Message deletion failed: <val1>",
    "dm_not_found": "Could not find user with ID <val1>",
    "dm_successful": "✉️ Sent DM to **<val1>**",
    "dm_failed": "User might have blocked DMs, or be a bot account.",
    "tell_guild_diff": "The channel is not in the same server (<val2> rather than <val1>)",
    "message_send_error": "Could not send message: <val1>",
    "tell_successful": "✉️ Successfully sent message to <val1>",
    "say_successful": "✉️ Successfully sent message",
    "tell_image_none": "I need you to upload a file with the command, otherwise use <val1>tell.",
    "colour_value_len": "Value must be either 3 or 6 digits long",
    "colour_invalid": "Invalid colour: <val1>\nValue must be either `random` or a HEX value",
    "removal_message_limit": "Too many messages to search given (<val1>/2,000)",
    "removal_forbidden": "I do not have permissions to delete messages.",
    "removal_error": "Error: <val1> (try a smaller search?)",
    "removal_success": "🚮 Successfully removed <val1> message(s).",
    "removal_reactions": "Successfully removed <val1> reactions.",
    "nickname_reset": "Reset **<val1>'s** nickname",
    "nickname_changed": "Changed **<val1>'s** nickname to **<val2>**",
    "unbanned": f"{emotes.Allow} Successfully unbanned <val1> (<val2>) for <val3> {emotes.BlobCatCoffee}",
    "mass_banned": f"Banned people for <val3> {emotes.BlobCatCoffee}\n{emotes.Allow} Successful: <val1>\n{emotes.Deny} Failed: <val2>",
    "ban_invalid": f"{emotes.Deny} I can't ban myself, nor my owners... {emotes.BlobCatPolice}",
    "self_harm_bad": f"{emotes.Deny} Self harm bad {emotes.BlobCatPolice}",
    "banned": f"{emotes.Allow} Successfully banned <val1> (<val2>) for <val3> {emotes.BlobCatCoffee}",
    "send_forbidden": f"{emotes.Deny} Failed to send message properly. I might be missing embed links or attach files permissions.",
    "kicked": f"{emotes.Allow} Successfully kicked <val1> (<val2>) for <val3> {emotes.BlobCatCoffee}",
    "generic": "Generic",
    "generic_info": "Developer: **<val1>**\nUptime: **<val2>**",
    "counts": "Counts",
    "counts_info": "Servers: **<val1>**\nUsers: **<val2>**\nAvg members / server: **<val3>**\nCommands: **<val4>**",
    "code_stats": "Code stats",
    "code_stats_info": "Files: **<val1>**\nLines: **<val2>**\nComments: **<val3>**\nFunctions: **<val4>**\nClasses: **<val5>**",
    "process": "Process",
    "process_info": "RAM: **<val1> MB**\nCPU: **<val2>%**",
    "counts2": "Server counts",
    "counts2_info": "Members: **<val1>**\nText Channels: **<val2>**\nCategories: **<val3>**\nVoice Channels: **<val4>**",
    "what_i_use": "What I use",
    "dates": "Dates",
    "dates_info": "First version: **<val1>**\nRelease v5.0: **<val2>**\nLast Update: **<val3>**",
    "about_suager": "ℹ About **<val1>** | **v<val2>**",
    "source": "These are the links that Suager started with, and you should check them out if you want to make your own bot.",
    "invite_bot": "<val1>, use this link to invite me:\n<https://discordapp.com/oauth2/authorize?permissions=<val2>&client_id=<val3>&scope=bot>",
    "invite_to_sl": "<val1>, here is a link to my server:",
    "invite_to_sl_failed": "I couldn't send the link to you. To avoid problems with server rules, I try to send the link to your DMs.",
    "ping1": f"{emotes.Loading} <val1> Pong\nMessage Send: undefined\nMessage Edit: undefined\nWS Latency: <val2>ms",
    "ping2": f"{emotes.Loading} <val1> Pong\nMessage Send: <val3>ms\nMessage Edit: undefined\nWS Latency: <val2>ms",
    "ping3": f"<val1> Pong\nMessage Send: <val3>ms\nMessage Edit: <val4>ms\nWS Latency: <val2>ms",
    "quote_begin": "**<val1>** once said...",
    "quote_author": "Quote author: <val1>",
    "respects1": "**<val1>** has paid their respects <val2>",
    "respects2": "**<val1>** has paid their respects for **<val2>** <val3>",
    "roll": "**<val1>** rolled **<val2>-<val3>** and got <val4>",
    "8ball": "**Question:** <val1>\n**Answer:** <val2>",
    "beer_self": "**<val1>**: paaaarty!🎉🍺",
    "beer_me": f"{emotes.Deny} But I'm underage...",
    "beer_bot": f"{emotes.Deny} It would probably be nice to give beer to <val1>, but I don't think the bot will respond to you...",
    "beer_offer1": "**<val1>**, you got a 🍺 offer from **<val2>**",
    "beer_offer2": "\n\nReason: <val1>",
    "beer_success": "**<val1>** and **<val2>** are enjoying a lovely beer together 🍻",
    "beer_timeout": "Well, it seems that **<val1>** didn't want to have a beer with you, **<val2>**...",
    "beer_offer3": "**<val1>** got a 🍺 from **<val2>**",
    "coin_flip": "The coin landed on **<val1>**",
    "coin_flip1": "Heads",
    "coin_flip2": "Tails",
    "vibe_check1": f"{emotes.Loading} Checking **<val1>**'s vibe...",
    "vibe_check2": "**<val1>** <val2> the vibe check...",
    "vibe_check3": "failed",
    "vibe_check4": "passed",
    "vote": "A <val1> has been started by <val2>: ```fix\n<val3>```",
    "vote1": "vote",
    "vote2": "petition",
    "pickle": "**<val1>'s** pickle size is **<val2>cm**",
    "gender_already_assigned": "<val1>, your gender is already set to <val2>. You can't change it...",
    "gender_invalid": "<val1> is not a valid gender. Valid choices: `<val2>`",
    "gender_invalid2": "Gender specified does not seem to be valid...",
    "gender_set": "<val1>, your gender has been set to <val2>. Database status: <val3>",
    "gender_force_set": "<val1>'s gender is now set to <val2>. Database status: <val3>",
    "image_not_created": "I could not create the image",
    "supreme_limit": "**<val1>**, the Supreme API is only limited to 500 characters...",
    "supreme_dark_light": "**<val1>**, you can't use both light and dark at the same time.",
    "pat_self": "Don't be like that...",
    "pat_suager": f"Thanks, <val1> :3 {emotes.AlexHeart} {emotes.AlexPat}",
    "inter_bot": "It's nice that you care about a bot, but I don't think <val1> will respond...",
    "pat": "**<val1>** got a pat from **<val2>**",
    "pat2": "<val1> has now received <val2> pats in this server",
    "alone": "Alone?",
    "hug_suager": f"*Hugs <val1> back* {emotes.AlexHeart}",
    "hug": "**<val1>** got a hug from **<val2>**",
    "hug2": "<val1> has now received <val2> hugs in this server",
    "cr_not_available": "Custom roles are not available in this server right now.",
    "cuddle_suager": f"*Cuddles <val1> back* {emotes.AlexHeart}",
    "cuddle": "**<val1>** got a cuddle from **<val2>**",
    "cuddle2": "<val1> has now received <val2> cuddles in this server",
    "lick_suager": "But why would you lick me, <val1>?",
    "lick_bot": "Why would you even lick a bot? It's not like <val1> would respond to you anyway.",
    "lick": "**<val1>** got licked by **<val2>**",
    "lick2": "<val1> has now been licked <val2> times in this server",
    "kiss_suager": "I was not programmed to feel love, <val1>...",
    "kiss_bot": "Bots like <val1> aren't made to feel love...",
    "kiss": "**<val1>** got kissed by **<val2>**",
    "kiss2": "<val1> has now got <val2> kisses in this server",
    "bite_suager": "But why would you bite me, <val1>?",
    "bite_bot": "Imagine biting a bot... It's not like <val1> would respond to you anyway.",
    "bite": "**<val1>** got bitten by **<val2>**",
    "bite2": "<val1> has now got bitten <val2> times in this server",
    "not_allowed": f"{emotes.Deny} You can't do that {emotes.BlobCatPolice}",
    "slap_suager": "<val1>, we are no longer friends.",
    "slap_bot": "What did <val1> even do to you?",
    "slap_bad": "Violence is not the answer, <val1>!",
    "slap": "**<val1>** got slapped by **<val2>**",
    "slap2": "<val1> has now got slapped <val2> times in this server",
    "how_are_you_gonna": f"{emotes.Deny} How are you gonna do that?",
    "smell_suager": "<val1>, why even?",
    "smell_bot": "Why would you smell <val1>?",
    "smell": "**<val1>** got <val3> by **<val2>**",
    "smell2": "<val1> has now got <val3> <val2> times in this server",
    "smelled": "smelled",
    "sniffed": "sniffed",
    "highfive_suager": "*High fives <val1> back*",
    "highfive_bot": "How is <val1> gonna high five you back?",
    "highfive": "**<val2>** gave **<val1>** a high five",
    "highfive2": "<val1> has now got <val2> high fives in this server",
    "poke_suager": "What do you want, <val1>?",
    "poke_bot": "What are you trying to achieve by poking <val1>?",
    "poke": "**<val1>** got poked by **<val2>**",
    "poke2": "<val1> has now got poked <val2> times in this server",
    "boop_bot": "What are you trying to achieve by doing that to <val1>?",
    "boop": "**<val1>** got booped by **<val2>**",
    "boop2": "<val1> has now got booped <val2> times in this server",
    "ship_suager": "I was never programmed to feel love...",
    "ship_self": "I don't think that's how it works",
    "ship": "Nice shipping!\nShip names: **<val1>** or **<val2>**\n",
    "ship2": "\n**<val1>** has now been shipped **<val2> times** in this server!",
    "ship3": "\n**<val1>** has now built **<val2> ships** in this server!",
    "spam_stats": "Spam stats for **<val1>** in **<val2>**",
    "top_counters": "Top spammers in **<val1>**",
    "sleepy": "**<val1>** is sleepy",
    "sleepy2": "<val1> has now been sleepy <val2> times in this server",
    "cry": "**<val1>** is crying",
    "cry2": "<val1> has now cried <val2> times in this server",
    "blush": "**<val1>** blushes",
    "blush2": "<val1> has now blushed <val2> times in this server",
    "smile": "**<val1>** smiles",
    "smile2": "<val1> has now smiled <val2> times in this server",
    "bang_suager": "Nope, find someone else.",
    "bang": "bang",
    "fuck": "fuck",
    "bang_out": f"{emotes.Scary} {emotes.NotLikeThis} **<val1>** is now <val3>ing **<val2>**...",
    "bang_counter": "\n**<val1>** has now got <val3>ed **<val2>** times in this server!",
    "bean_not_allowed": f"{emotes.Deny} You are not allowed to do that {emotes.BlobCatPolice}",
    "bean_suager": f"{emotes.Deny} You can't bean me",
    "bean_owner": f"{emotes.Deny} Imagine beaning the owner, lol",
    "bean": f"{emotes.Allow} **<val1>** has been dismissed from **<val2>**.",
    "bean3": "\n**<val1>** has now been beaned **<val2> times** in this server",
    "bean2": f"{emotes.Deny} **<val1>** has been dismissed from **<val2>**.",
    "bad_suager": "If you think I'm bad, why am I still in this server?",
    "eat_allowed": "You can only eat: cookie, carrot, fruit, lemon",
    "cookie_singular": "cookie",
    "cookie_plural": "cookies",
    "carrot_singular": "carrot",
    "carrot_plural": "carrots",
    "fruit_plural": "fruits",
    "fruit_singular": "fruit",
    "lemon_singular": "lemon",
    "lemon_plural": "lemons",
    "eat_none": f"{emotes.Deny} You don't have any <val1> right now...",
    "eat_none_left": f"{emotes.Deny} You don't have any <val1> left...",
    "eat": "**<val1>**, you just ate a **<val2>**. You have **<val3>** left.",
    "no_greedy": "Don't be greedy, **<val1>**!",
    "give_food": "**<val2>** just got a <val3> from **<val1>**",
    "food_counter": "\n**<val1>** now has **<val2> <val3>** in this server",
    "bad_self": emotes.AlexPat,
    "tz_set": "<val1>, your timezone has been set to **<val2>**.\nDB status: <val3>",
    "tz_invalid": "The timezone you specified (<val1>) was not found. Attached below is the list of pytz timezones.",
    "time_local": "\n<val1>: **<val2>**",
    "counters_disabled": "Counters are hidden in this server.",
    "channel_must_be_nsfw": "You can only use this command in an NSFW channel",
    "allowed_filters": "This is the list of filters: `<val1>`",
    "invalid_colour": "Invalid value specified, using default...",
    "color": "color",
    "colour": "colour",
    "invalid_colour2": "Invalid <val1>: <val3>\n<val2> must be either `random` or a HEX value",
    "col_error": "Something went wrong, try again later",
    "hex_value": "Hex value",
    "rgb_value": "RDB value",
    "integer": "Integer",
    "brightness": "Brightness",
    "font_col": "Font <val1>",
    "col_error2": "An error occurred. Are you sure the colour is a HEX value (0-9 and A-F)?",
    "col_3": "Remove the `#`...",
    "crank_font": "Updated your font colour to <val1>\nDB status: <val2>",
    "crank_pb": "Updated your progress bar colour to <val1>\nDB status: <val2>",
    "crank_bg": "Updated your background colour to <val1>\nDB status: <val2>",
    "bot_xp": "Bots are cheating, so I don't store their XP",
    "su_locale": "Updated locale to <val1>\nDB status: <val2>",
    "su_currency": "Updated currency to <val1>\nDB status: <val2>",
    "su_pa": "Added <val1> to this server's custom prefixes\nDB status: <val2>",
    "su_pr": "Removed <val1> from this server's custom prefixes\nDB status: <val2>",
    "su_prf": "<val1> does not seem to be a prefix in this server.",
    "su_pde": "Default prefixes are now enabled in this server\nDB status: <val1>",
    "su_pdd": "Default prefixes are now disabled in this server\nDB status: <val1>",
    "su_asa": "#<val1> has been added to the XP Anti-Spam list\nDB status: <val2>",
    "su_asaa": "#<val1> is already on the XP Anti-Spam list.",
    "su_asd": "#<val1> has been removed from the XP Anti-Spam list\nDB status: <val2>",
    "su_asdf": "#<val1> does not seem to be in the XP Anti-Spam list.",
    "su_le": "Leveling is now enabled\nDB status: <val1>",
    "su_ld": "Leveling is now disabled\nDB status: <val1>",
    "su_lm": "XP multiplier is now <val1>\nDB status: <val2>",
    "su_lm2": "The level up message is now:\n<val1>\nDB status: <val2>",
    "su_lia": "Leveling is now ignored in #<val1>\nDB status: <val2>",
    "su_liaa": "Leveling is already ignored in #<val1>.",
    "su_lid": "Leveling is no longer ignored in #<val1>\nDB status: <val2>",
    "su_lidf": "Leveling is not ignored in #<val1>.",
    "su_la": "Level ups will now be announced in #<val1>.\nDB status: <val2>",
    "su_lar": "Level ups will now be announced in the channel they occur in.\nDB status: <val1>",
    "su_lra_nl": "Level cannot be negative.",
    "su_lra_hl": "Level cannot be above max level (<val1>).",
    "su_lra_ra": "This role is already rewarded.",
    "su_lra_la": "There is already a reward at this level.",
    "su_lra": "Role <val1> is now rewarded at level <val2>.\nDB status: <val3>",
    "su_lrd_nr": "There are no level rewards to begin with...",
    "su_lrd": "Role <val1> has been removed from level rewards\nDB status: <val2>",
    "su_lrdf": "Role <val1> was not removed from level rewards. The role is probably not rewarded.",
    "su_sa_nc": "Cost cannot be negative.",
    "su_sa_ra": "This role is already being sold.",
    "su_sa": "Role <val1> can now be bought for <val2>.\nDB status: <val3>",
    "su_sd_nr": "The shop seems to be empty already...",
    "su_sd": "Role <val1> has been removed from the shop.\nDB status: <val2>",
    "su_sdf": "Role <val1> was not removed from the shop. It is probably not sold.",
    "economy_lb": "Top users in <val1> - Sorted by money\nYour place: <val2>\nShowing places <val4> to <val5> of <val6>\n<val3>```",
}
