from utils import emotes

data = {
    "admin_source": f"{emotes.Meh} Нет, **<val1>**, но ты создал исходный код.",
    "admin_yes": f"{emotes.Allow} Да, **<val1>**, ты мой создатель.",
    "admin_no": f"{emotes.Deny} Нет, **<val1>**, отвали!",
    "input_too_long": "Ты хотел, чтобы комманда вывела более 2000 символов в ответ?\nНу, молодец. Ты всё сломал. Теперь займись чем-нибудь "
                      "более интересным.",
    "error_occurred": f"{emotes.Deny} Произошла ошибка, попробуй снова позже...\n`<val1>`",
    "command_cooldown": f"{emotes.Deny} Эта комманда на кулдауне... Попробуй снова через <val1>",
    "max_concurrency": f"{emotes.Deny} Эта комманда не может быть использована прямо сейчас, попробуй позже...",
    "server_locked": f"{emotes.Deny} Эта команда заблокирована на этом сервере.",
    "channel_locked": f"{emotes.Deny} Используй канал для ботов, а не этот...",
    # "time_command": f"**<val3>**, сейчас:\n**<val2>** в Логове Сенко\n**<val1>** на Земле.",
    "time_command": f"**<val3>**, сейчас:\nВ Логове Сенко: **<val2>**\nМестное время: **<val1>**\nUTC: **<val4>**",
    "settings_template": "Это шаблон настроек.\nЧтобы загрузить: `<val1>settings upload`",
    "settings_template_detailed": "Это шаблон настроек.\nЧтобы загрузить: `<val1>settings upload`\nДля уровней, [USER] выводит имя пользователя, "
                                  "а [MENTION] @упоминает его.",
    "settings_current": "Текущие настройки в **<val1>**\nИспользуй `<val2>settings template` для шаблона.",
    "settings_upload_no1": f"{emotes.Deny} Это должен быть файл JSON.",
    "settings_upload_no2": f"{emotes.Deny} При получении файла произошла ошибка.",
    "settings_upload_no3": f"{emotes.Deny} Должен быть ровно один файл JSON.",
    "settings_upload_no4": f"{emotes.Deny} Ошибка при загрузке файла:\n`<val1>`",
    "settings_upload_yes": f"{emotes.Allow} Настройки были обновлены.\nСтатус базы данных: <val1>",
    "premium": "Какой ещё премиум для этого бота?",
    "eat_adde": "<val1>, Adde är inte kyckling nudlar, sluta äta honom.",
    "birthday_today": "С днём рождения, <val1>, наслаждайся своей ролью сегодня! 🎂🎉",
    "birthday_self": f"Мой день рождения **13го мая**, спасибо, что спросил. {emotes.AlexHeart}",
    "birthday_none": "**<val1>** не сохранил его/её день рождения :(",
    "birthday_you": "У **тебя** день рождения **<val1>**",
    "birthday_other": "У **<val1>** день рождения **<val2>**",
    "birthday_already_set": "Твой день рождения уже сохранён: **<val1>**\nЧтобы изменить его, спроси владельца бота.",
    "birthday_no": "Нужно ввести дату вместе с коммандой... `[ ДД/ММ ]`",
    "birthday_confirm": "**<val1>**, ты подтверждаешь, что твой день рождения **<val2>**?\nВведи `<val3>`, чтобы подтвердить твой выбор.\n"
                        "(ЗАМЕТКА: Чтобы изменить дату в будущем, тебе нужно будет отправить верную дату владельцу бота)",
    "birthday_no2": "~~<val1>~~\n\nНу, ты решил не отвечать...",
    "birthday_set": "Готово, теперь твой день рождения (**<val1>**) сохранён в моей базе данных 🎂",
    "avatar": "Аватар пользователя **<val1>**\n<val2>",
    "roles_in_server": "Роли на сервере **<val1>**",
    "user_joined_at": "**<val1>** зашёл(ла) в **<val2>**: <val3>",
    "username": "Имя пользователя",
    "nickname": "Никнейм",
    "user_id": "ID пользователя",
    "created_at": "Время создания",
    "joined_at": "Зашёл(ла) на сервер",
    "current_status": "Текущий статус",
    "current_activity": "Текущая активность",
    "no": "Нет",
    "roles": "Роли",
    "about_user": "ℹ О **<val1>**",
    "emoji_desc": "Название: <val1>\nID: <val2>\nАнимировано: <val3>\nСервер: <val4>\nВремя создания: <val5>\n[Скопировать ссылку](<val6>)",
    "only_in_senko_lair": f"{emotes.Deny} Эта комманда доступна только в Логове Сенко (Senko Lair).",
    "server_name": "Название сервера",
    "server_id": "ID сервера",
    "owner": "Владелец",
    "members": "Кол-во участников",
    "bots": "Кол-во ботов",
    "region": "Регион",
    "ban_count": "Кол-во банов",
    "access_denied": "Доступ запрещён",
    "channels": "Кол-во каналов",
    "channels2": "<val1> текстовых каналов\n<val2> категорий\n<val3> голосовых каналов",
    "about_server": "О **<val1>**",
    "server_icon": "Иконка сервера **<val1>**\n<val2>",
    "bots_in_server": "Боты в **<val1>**: ```ini\n<val2>```",
    "status_of_users": "Статус участников **<val1>**",
    "total_members": "Всего участников",
    "status": "Статус",
    "status2": "<val1> В сети: <val2> - <val3>%, из которых:\nНа телефоне: <val4> | На ПК: <val5> | В браузере: <val6>\n\n"
               "<val7> Не активны: <val8> - <val9>%, из которых:\nНа телефоне: <val10> | На ПК: <val11> | В браузере: <val12>\n\n"
               "<val13> Не беспокоить: <val14> - <val15>%, из которых:\nНа телефоне: <val16> | На ПК: <val17> | В браузере: <val18>\n\n"
               "<val19> Не в сети: <val20> - <val21>%",
    "activities": "Активность",
    "activities2": "Из <val1> человек в сети:\n<val2> Играют в игру: <val3> - <val4>%\n<val5> Пользовательский статус: <val6> - <val7>%\n"
                   "<val8> Стримят: <val9> - <val10>%\n<val11> Слушают музыку: <val12> - <val13>%\n<val14> Ничего не делают: <val15> - <val16>%",
    "default_prefixes": "Префиксы по умолчанию",
    "custom_prefixes": "Пользовательские префиксы",
    "server_prefixes": "Префиксы бота в **<val1>**",
    "bots_money": "У ботов не может быть денег, потому что они читеры. Не беспокойся, Regaus даёт мне деньги.",
    "no_money": "Похоже у <val1> вообще нет денег...",
    "balance": "У **<val1>** **<val2><val3>** в **<val4>**",
    "donate_negative": f"{emotes.Deny} Хорошая попытка, <val1>.",
    "donate_self": f"{emotes.Deny} <val1> настолько щедр, что пытается дать деньги самому себе.",
    "no_money2": f"{emotes.Deny} У тебя и так денег нет...",
    "no_money3": f"{emotes.Deny} <val1>, у тебя недостаточно денег для этого...",
    "donate_yes": f"{emotes.Allow} <val1> дал <val2><val3> <val4>. {emotes.AlexHeart}",
    "money_self": "Достаточно",
    "donated_self": "Никогда не считал",
    "more_than_you": "Больше, чем у тебя",
    "more_than_you2": "Больше, чем ты",
    "profile": "Профиль **<val1>** в **<val2>**",
    "money": "Деньги",
    "donated": "Отдано",
    "shop_empty": "Похоже, здесь ничего не продаётся...",
    "shop": "Магазин сервера **<val1>**",
    "shop_item": "<@&<val2>>: <val1><val3>\n",
    "buy_role_no": f"{emotes.Deny} <val1>, роль <val2> не продаётся...",
    "buy_role_confirm": "<val1>, ты уверен(а), что хочешь купить роль <val2> за <val3><val4>? Напиши `да`, чтобы подтвердить.",
    "buy_role_no2": "~~<val1>~~\n\nЯ принимаю отсутствие ответа как нет...",
    "buy_role_no3": f"{emotes.Deny} <val1>, у тебя уже есть роль <val2>...",
    "buy_role_no4": f"{emotes.Deny} <val1>, у тебя недостаточно денег, чтобы купить роль <val2>... (<val3>/<val4><val5>)",
    "buy_role_no5": f"{emotes.Deny} <val1>, у тебя и так нет денег...",
    "buy_role_forbidden": f"{emotes.Deny} У меня нет прав дать тебе эту роль - обратись к администраторам...",
    "buy_role_success": f"{emotes.Allow} <val1> успешно купил(а) роль <val2> за <val3><val4>.",
    "none": "Нет",
    "boosts": "Бусты сервера",
    "boosts2": "Бустов: <val1> - Уровень <val2>\nВсего бустеров: <val3>",
    "emotes": "Эмодзи",
    "emotes2": "<val3>/<val1> неанимированных\n<val2>/<val1> анимированных\n<val4> всего",
    "shard_id": "ID шарда",
    "verification_level": "Уровень проверки",
    "low": "Низкий",
    "medium": "Средний",
    "high": "Высокий",
    "extreme": "Экстремальный",
    "level_reward_failed": f"{emotes.Deny} <val1> должен получить награду за уровень, но у меня нет разрешений, чтобы это сделать.",
    "rewards_none": "Похоже, на этом сервере нет никаких наград за уровни.",
    "rewards_title": "Rewards for having no life in <val1>",
    "rewards_reward": "<val1>-й уровень: <@&<val2>>\n",
    "rank_place_unknown": "Неизвестное",
    "rank_place_num": "<val1>-е",
    "rank_level": "<val1>-й уровень",
    "rank_rank": "<val1> место",
    "rank_xp": "<val1>/<val2> опыта\nПрогресс: <val3>%",
    "rank_xp_self": "9,999,999,999,999 опыта",
    "rank_user": "Ранг пользователя **<val1>** в **<val2>**",
    "rank_self": "\nТак это же я! Зачем играть честно?",
    "nl_no_data": "У меня нет никаких данных о твоём уровне прямо сейчас...",
    "max_level": "Максимальный уровень: <val1>.",
    "xl_index_error": "Произошла ошибка при получении данных о уровне <val1>. Убедись, что он ниже максимального (<val2>).",
    "xp_level_base": "<val1>: Чтобы достичь **<val2>**-го уровня, тебе нужно **<val3> опыта**",
    "xp_level_extra": "\nОпыта до уровня: **<val1>**\nОсталось времени: примерно от **<val2> до <val3>**",
    "next_level_data": "**<val1>**: у тебя сейчас **<val2>/<val3>** опыта.\nТебе нужно ещё **<val4>**, чтобы достичь **<val5>**-го уровня. "
                       "(Прогресс: **<val6>%**).\nГоворить придётся примерно: от **<val7> до <val8>**",
    "levels_no_data": "У меня нет никаких данных об этом сервере... Странно.",
    "levels_lb": "Топ пользователей в <val1> - Отсортированно по опыту\nТвоё место: <val2>\nПоказаны с <val4>-го пo <val5>-е места\n<val3>```",
    "levels_global": "Топ пользователей глобально - Отсортированно по опыту\nТвоё место: <val1>\nПоказаны с <val3>-го пo <val4>-е места\n<val2>```",
    "experience": "Опыт",
    "level": "Уровень",
    "higher_than_yours": "Выше твоего",
    "rank_progress": "Прогресс до следующего уровня",
    "rank_progress2": "<val1>% - <val2> опыта до след. уровня",
    "xp_per_message": "Опыта за сообщение",
    "global_rank": "У **<val1>** **<val2> опыта** глобально, и он(а) занимает **<val3>** место в таблице лидеров.",
    "love_locked": f"{emotes.Deny} Представь, что ты настолько долго раздражал Regaus'а, что он для тебя заблокировал эту комманду, <val1>.",
    "bad_locked": "Сам ты как будто весь примерный, <val1>...",
    "server_banner": "Баннер сервера **<val1>**\n<val2>",
    "server_splash": "Фон приглашения сервера **<val1>**\n<val2>",
    "server_banner_none": "У сервера **<val1>** нет баннера",
    "server_splash_none": "У сервера **<val1>** нет фона приглашения",
    "time_since": "Текущее время: **<val1>**\nУказанное время: **<val2>**\nРезультат: **<val3>**",
    "time_since_error": "Произошла ошибка:\n<val1>",
    "luas": "Данные о <val1>:\n<val2>\n<val3>",
    "current_weather": "Текущая погода",
    "temperature": "Температура",
    "pressure": "Давление",
    "humidity": "Влажность",
    "wind_speed": "Скорость ветра",
    "cloud_cover": "Облачность",
    "sunrise": "Восход",
    "sunset": "Закат",
    "weather_error": f"{emotes.Deny} не найдено данных о погоде для <val1>:\n<val2>: <val3>",
    "weather_output": "<val1> Погода в **<val2>, <val3>**",
    "weather_output2": "Местное время: **<val1>**",
    "iq": "IQ **<val1>** равен **<val2>**",
    "hot_calc": "**<val1>** на **<val2>%** горячий <val3>",
    "love_calc": "Уровень любви между <val1> и <val2> равен **<val3>**%",
    "bots_love": "Боты не ощущают любви к простым пользователям...",
    "already_taken": "<val1>, Я уже занят...",
    "lc_same": "Я думаю это не так работает...",
    "baby_rate": "Шанс, что у <val1> и <val2> будут дети равен **<val3>**%",
    "baby_rate_bot": "Ботов создавали не для того, чтобы у них были дети...",
    "baby_rate_self": "<val1>, я был не для этого создан...",
    "rate": "Я оценю <val1> **<val2>/100**",
    "message_del_error": "Не удалось удалить сообщение: <val1>",
    "dm_not_found": "Пользователь с ID <val1> не был найден",
    "dm_successful": "✉️ Отправил ЛС к **<val1>**",
    "dm_failed": "У пользователя могут быть заблокированы личные сообщения, или он(а) - бот.",
    "tell_guild_diff": "Этот канал в другом сервере (<val2>, а не <val1>)",
    "message_send_error": "Сообщение не было отправлено: <val1>",
    "tell_successful": "✉️ Сообщение в <val1> было успешно отправлено",
    "say_successful": "✉️ Сообщение было успешно отправлено",
    "tell_image_none": "Загрузи файл вместе с командой, иначе используй <val1>tell.",
    "colour_value_len": "Значение должно быть 3 или 6 цифрами по длине",
    "colour_invalid": "Неверный цвет: <val1>\nЗначение должно быть либо `random`, либо HEX-значением",
    "removal_message_limit": "Слишком много сообщений для поиска (<val1>/2,000)",
    "removal_forbidden": "У меня нет разрешения удалять сообщения.",
    "removal_error": "Ошибка: <val1> (попробуй поиск поменьше?)",
    "removal_success": "🚮 Успешно удалено <val1> сообщений(е/я).",
    "removal_reactions": "Удалено <val1> реакций.",
    "nickname_reset": "Никнейм **<val1>** сброшен",
    "nickname_changed": "Никнейм **<val1>** теперь **<val2>**",
    "unbanned": f"{emotes.Allow} <val1> (<val2>) был разбанен за <val3> {emotes.BlobCatCoffee}",
    "mass_banned": f"Забанил пользователей за <val3> {emotes.BlobCatCoffee}\n{emotes.Allow} Удачно: <val1>\n{emotes.Deny} Неудачно: <val2>",
    "ban_invalid": f"{emotes.Deny} Я не могу забанить себя, или моих создателей... {emotes.BlobCatPolice}",
    "self_harm_bad": f"{emotes.Deny} Вред себе = плохо {emotes.BlobCatPolice}",
    "banned": f"{emotes.Allow} <val1> (<val2>) был забанен за <val3> {emotes.BlobCatCoffee}",
    "send_forbidden": f"{emotes.Deny} Не смог отправить сообщение. Возможно, у меня нет прав на вставку ссылок или прикрепление файлов.",
    "kicked": f"{emotes.Allow} <val1> (<val2>) был выгнан за <val3> {emotes.BlobCatCoffee}",
    "generic": "Общее",
    "generic_info": "Разработчик: **<val1>**\nВремя работы: **<val2>**",
    "counts": "Счётчики",
    "counts_info": "Серверов: **<val1>**\nПользователей: **<val2>**\nСр. участников на сервер: **<val3>**\nКомманд: **<val4>**",
    "code_stats": "Статистика кода",
    "code_stats_info": "Файлов: **<val1>**\nСтрок: **<val2>**\nКомментариев: **<val3>**\nФункций: **<val4>**\nКлассов: **<val5>**",
    "process": "Процесс",
    "process_info": "Оп. Памяти: **<val1> MB**\nЦП: **<val2>%**",
    "counts2": "Счётчики серверов",
    "counts2_info": "Участников: **<val1>**\nТекстовых каналов: **<val2>**\nКатегорий: **<val3>**\nГолосовых каналов: **<val4>**",
    "what_i_use": "Что я использую",
    "dates": "Даты",
    "dates_info": "Первая версия: **<val1>**\nРелиз v5ю0: **<val2>**\nПоследнее обловление: **<val3>**",
    "about_suager": "ℹ О **<val1>** | **v<val2>**",
    "source": "Отсюда началась история бота Suager, и ты с их помощью можешь создать своего бота.",
    "invite_bot": "<val1>, используй данную ссылку, чтобы добавить меня в свой сервер:\n"
                  "<https://discordapp.com/oauth2/authorize?permissions=<val2>&client_id=<val3>&scope=bot>",
    "invite_to_sl": "<val1>, вот ссылка на мой сервер:",
    "invite_to_sl_failed": "Ссылка не была отправлена. Чтобы избежать проблем с правилами серверов, я отправляю её в ЛС.",
    "ping1": f"{emotes.Loading} <val1> Понг\nОтправка сообщения: неизвестно\nИзменение сообщения: неизвестно\nЗадержка WS: <val2>ms",
    "ping2": f"{emotes.Loading} <val1> Понг\nОтправка сообщения: <val3>ms\nИзменение сообщения: неизвестно\nЗадержка WS: <val2>ms",
    "ping3": f"<val1> Понг\nОтправка сообщения: <val3>ms\nИзменение сообщения: <val4>ms\nЗадержка WS: <val2>ms",
    "quote_begin": "**<val1>** однажды сказал...",
    "quote_author": "Автор цитаты: <val1>",
    "respects1": "**<val1>** отдал честь <val2>",
    "respects2": "**<val1>** отдал честь за **<val2>** <val3>",
    "roll": "**<val1>** бросил **<val2>-<val3>** и получил <val4>",
    "8ball": "**Вопрос:** <val1>\n**Ответ:** <val2>",
    "beer_self": "**<val1>**: вечеринка!🎉🍺",
    "beer_me": f"{emotes.Deny} Но я несовершеннолетний...",
    "beer_bot": f"{emotes.Deny} Наверно, было бы неплохо дать пиво <val1>, но я не думаю, что бот ответит тебе...",
    "beer_offer1": "**<val1>** получил предложение 🍺 от **<val2>**",
    "beer_offer2": "\n\nПричина: <val1>",
    "beer_success": "**<val1>** и **<val2>** вместе наслаждаются пивом 🍻",
    "beer_timeout": "Ну, судя по всему, **<val1>** не хочет пива с тобой, **<val2>**...",
    "beer_offer3": "**<val1>** получил 🍺 от **<val2>**",
    "coin_flip": "Монета приземлилась на **<val1>**",
    "coin_flip1": "орёл",
    "coin_flip2": "решку",
    "vibe_check1": f"{emotes.Loading} Проверка вайба **<val1>**...",
    "vibe_check2": "**<val1>** <val2> проверку вайба...",
    "vibe_check3": "провалил",
    "vibe_check4": "прошёл",
    "vote": "<val2> начал <val1>: ```fix\n<val3>```",
    "vote1": "голосование",
    "vote2": "петицию",
    "pickle": "Размер огурца **<val1>** **<val2>см**",
    "gender_already_assigned": "<val1>, твой пол уже сохранён - <val2>. ТЫ не можешь его изменить...",
    "gender_invalid": "<val1> Не является верным выбором. Ты можешь выбрать из: `<val2>`",
    "gender_invalid2": "Указанный пол не является верным...",
    "gender_set": "<val1>, твой пол был сохранён как <val2>. Статус базы данных: <val3>",
    "gender_force_set": "Пол <val1> теперь <val2>. Статус базы данных: <val3>",
    "image_not_created": "Изображение не было создано",
    "supreme_limit": "**<val1>**, API поддерживает только до 500 символов...",
    "supreme_dark_light": "**<val1>**, нельзя использовать светлый и темный режимы одновременно.",
    "pat_self": "Не будь таким...",
    "pat_suager": f"Спасибо, <val1> :3 {emotes.AlexHeart} {emotes.AlexPat}",
    "inter_bot": "Хорошо, что ты заботишься о боте, но я не думаю, что <val1> ответит...",
    "pat": "**<val2>** погладил(а) **<val1>**",
    "pat2": "<val1> погладили <val2> раз(а) на этом сервере",
    "alone": "Одиноко?",
    "hug_suager": f"*Обнимает <val1> в ответ* {emotes.AlexHeart}",
    "hug": "**<val2>** обнял(а) **<val1>**",
    "hug2": "<val1> обняли <val2> раз(а) на этом сервере",
    "cr_not_available": "Пользовательские роли не доступны на этом сервере.",
    "cuddle_suager": f"*Обнимает <val1> в ответ* {emotes.AlexHeart}",
    "cuddle": "**<val2>** сильно обнял(а) **<val1>**",
    "cuddle2": "<val1> обняли <val2> раз(а) на этом сервере",
    "lick_suager": "Зачем меня лизать, <val1>?",
    "lick_bot": "Зачем вообще лизать бота? <val1> все равно вряд ли тебе ответит.",
    "lick": "**<val2>** лизнул(а) **<val1>**",
    "lick2": "<val1> лизнули <val2> раз(а) на этом сервере",
    "kiss_suager": "Я не был запрограммирован чувствовать любовь, <val1>...",
    "kiss_bot": "Боты вроде <val1> не были созданы, чтобы чувствовать любовь...",
    "kiss": "**<val2>** поцеловал(а) **<val1>**",
    "kiss2": "<val1> поцеловали <val2> раз(а) на этом сервере",
    "bite_suager": "Зачем меня кусать, <val1>?",
    "bite_bot": "Я думаю, что даже если ты укусишь <val1>, бот тебе все равно не ответит.",
    "bite": "**<val2>** укусил(а) **<val1>**",
    "bite2": "<val1> укусили <val2> раз(а) на этом сервере",
    "not_allowed": f"{emotes.Deny} Ты не можешь этого делать {emotes.BlobCatPolice}",
    "slap_suager": "<val1>, мы больше не друзья.",
    "slap_bot": "Что тебе <val1> сделал?",
    "slap_bad": "Жестокость - не ответ, <val1>!",
    "slap": "**<val2>** дал(а) пощёчину **<val1>**",
    "slap2": "<val1> получил(а) леща <val2> раз(а) на этом сервере",
    "how_are_you_gonna": f"{emotes.Deny} И как ты собираешься это сделать?",
    "smell_suager": "<val1>, зачем?",
    "smell_bot": "Зачем нюхать <val1>?",
    "smell": "**<val2>** <val3>(а) **<val1>**",
    "smell2": "<val1> <val3>и <val2> раз(а) на этом сервере",
    "smelled": "нюхнул",
    "sniffed": "нюхнул",
    # todo: перевести эту хрень
    "highfive_suager": "*High fives <val1> back*",
    "highfive_bot": "How is <val1> gonna high five you back?",
    "highfive": "**<val2>** gave **<val1>** a high five",
    "highfive2": "<val1> has now got <val2> high fives in this server",
    "poke_suager": "What do you want, <val1>?",
    "poke_bot": "What are you trying to achieve by poking <val1>?",
    "poke": "**<val1>** got poked by **<val2>**",
    "poke2": "<val1> has now got poked <val2> times in this server",
    "boop_bot": "What are you trying to achieve by doing that to <val1>?",
    "boop": "**<val1>** got booped by **<val2>**",
    "boop2": "<val1> has now got booped <val2> times in this server",
    "ship_suager": "I was never programmed to feel love...",
    "ship_self": "I don't think that's how it works",
    "ship": "Nice shipping!\nShip names: **<val1>** or **<val2>**\n",
    "ship2": "\n**<val1>** has now been shipped **<val2> times** in this server!",
    "ship3": "\n**<val1>** has now built **<val2> ships** in this server!",
    "spam_stats": "Spam stats for **<val1>** in **<val2>**",
    "top_counters": "Top spammers in **<val1>**",
    "sleepy": "**<val1>** is sleepy",
    "sleepy2": "<val1> has now been sleepy <val2> times in this server",
    "cry": "**<val1>** is crying",
    "cry2": "<val1> has now cried <val2> times in this server",
    "blush": "**<val1>** blushes",
    "blush2": "<val1> has now blushed <val2> times in this server",
    "smile": "**<val1>** smiles",
    "smile2": "<val1> has now smiled <val2> times in this server",
    "bang_suager": "Nope, find someone else.",
    "bang": "bang",
    "fuck": "fuck",
    "bang_out": f"{emotes.Scary} {emotes.NotLikeThis} **<val1>** is now <val3>ing **<val2>**...",
    "bang_counter": "\n**<val1> **has now got <val3>ed **<val2>** times in this server!",
    "bean_not_allowed": f"{emotes.Deny} You are not allowed to do that {emotes.BlobCatPolice}",
    "bean_suager": f"{emotes.Deny} You can't bean me",
    "bean_owner": f"{emotes.Deny} Imagine beaning the owner, lol",
    "bean": f"{emotes.Allow} **<val1>** has been dismissed from **<val2>**.",
    "bean3": "\n**<val1>** has now been beaned **<val2> times** in this server",
    "bean2": f"{emotes.Deny} **<val1>** has been dismissed from **<val2>**.",
    "bad_suager": "If you think I'm bad, why am I still in this server?",
    "eat_allowed": "You can only eat: cookie, carrot, fruit, lemon",
    "cookie_singular": "cookie",
    "cookie_plural": "cookies",
    "carrot_singular": "carrot",
    "carrot_plural": "carrots",
    "fruit_plural": "fruits",
    "fruit_singular": "fruit",
    "lemon_singular": "lemon",
    "lemon_plural": "lemons",
    "eat_none": f"{emotes.Deny} You don't have any <val1> right now...",
    "eat_none_left": f"{emotes.Deny} You don't have any <val1> left...",
    "eat": "**<val1>**, you just ate a **<val2>**. You have **<val3>** left.",
    "no_greedy": "Don't be greedy, **<val1>**!",
    "give_food": "**<val2>** just got a <val3> from **<val1>**",
    "food_counter": "\n**<val1>** now has **<val2> <val3>** in this server",
    "bad_self": emotes.AlexPat,
    "tz_set": "<val1>, your timezone has been set to **<val2>**.\nDB status: <val3>",
    "tz_invalid": "The timezone you specified <val1> was not found. Attached below is the list of pytz timezones.",
    "time_local": "\n<val1>: **<val2>**",
    "counters_disabled": "Counters are hidden in this server - you can still check them with `<val1>counters`.",
    "channel_must_be_nsfw": "You can only use this command in an NSFW channel",
    "allowed_filters": "This is the list of filters: `<val1>`",
    "invalid_colour": "Invalid value specified, using default...",
    "color": "color",
    "colour": "colour",
    "invalid_colour2": "Invalid <val1>: <val3>\n<val2> must be either `random` or a HEX value",
    "col_error": "Something went wrong, try again later",
    "hex_value": "Hex value",
    "rgb_value": "RDB value",
    "integer": "Integer",
    "brightness": "Brightness",
    "font_col": "Font <val1>",
    "col_error2": "An error occurred. Are you sure the colour is a HEX value (0-9 and A-F)?",
    "col_3": "Remove the `#`...",
    "crank_font": "Updated your font colour to <val1>\nDB status: <val2>",
    "crank_pb": "Updated your progress bar colour to <val1>\nDB status: <val2>",
    "crank_bg": "Updated your background colour to <val1>\nDB status: <val2>",
    "bot_xp": "Bots are cheating, so I don't store their XP",
    "su_locale": "Updated locale to <val1>\nDB status: <val2>",
    "su_currency": "Updated currency to <val1>\nDB status: <val2>",
    "su_pa": "Added <val1> to this server's custom prefixes\nDB status: <val2>",
    "su_pr": "Removed <val1> from this server's custom prefixes\nDB status: <val2>",
    "su_prf": "<val1> does not seem to be a prefix in this server.",
    "su_pde": "Default prefixes are now enabled in this server\nDB status: <val1>",
    "su_pdd": "Default prefixes are now disabled in this server\nDB status: <val1>",
    "su_asa": "#<val1> has been added to the XP Anti-Spam list\nDB status: <val2>",
    "su_asd": "#<val1> has been removed from the XP Anti-Spam list\nDB status: <val2>",
    "su_asdf": "#<val1> does not seem to be in the XP Anti-Spam list.",
    "su_le": "Leveling is now enabled\nDB status: <val1>",
    "su_ld": "Leveling is now disabled\nDB status: <val1>",
    "su_lm": "XP multiplier is now <val1>\nDB status: <val2>",
    "su_lm2": "The level up message is now:\n<val1>\nDB status: <val2>",
    "su_lia": "Leveling is now ignored in #<val1>\nDB status: <val2>",
    "su_lid": "Leveling is no longer ignored in #<val1>\nDB status: <val2>",
    "su_lidf": "Leveling is not ignored in #<val1>.",
    "su_la": "Level ups will now be announced in #<val1>.\nDB status: <val2>",
    "su_lar": "Level ups will now be announced in the channel they occur in.\nDB status: <val1>",
    "su_lra_nl": "Level cannot be negative.",
    "su_lra_hl": "Level cannot be above max level (<val1>).",
    "su_lra_ra": "This role is already rewarded.",
    "su_lra_la": "There is already a reward at this level.",
    "su_lra": "Role <val1> is now rewarded at level <val2>.\nDB status: <val3>",
    "su_lrd_nr": "There are no level rewards to begin with...",
    "su_lrd": "Role <val1> has been removed from level rewards\nDB status: <val2>",
    "su_lrdf": "Role <val1> was not removed from level rewards. The role is probably not rewarded.",
    "su_sa_nc": "Cost cannot be negative.",
    "su_sa_ra": "This role is already being sold.",
    "su_sa": "Role <val1> can now be bought for <val2>.\nDB status: <val3>",
    "su_sd_nr": "The shop seems to be empty already...",
    "su_sd": "Role <val1> has been removed from the shop.\nDB status: <val2>",
    "su_sdf": "Role <val1> was not removed from the shop. It is probably not sold.",
}
