from utils import emotes

data = {
    "admin_source": f"{emotes.Meh} Нет, **<val1>**, но ты создал исходный код.",
    "admin_yes": f"{emotes.Allow} Да, **<val1>**, ты мой создатель.",
    "admin_no": f"{emotes.Deny} Нет, **<val1>**, отвали!",
    # "use_bot_commands": f"{emotes.Deny} Используй канал для комманд для этого...",
    "input_too_long": "Ты хотел, чтобы комманда вывела более 2000 символов в ответ?\nНу, молодец. Ты всё сломал. Теперь займись чем-нибудь "
                      "более интересным.",
    "error_occurred": f"{emotes.Deny} Произошла ошибка, попробуй снова позже...\n`<val1>`",
    "command_cooldown": f"{emotes.Deny} Эта комманда на кулдауне... Попробуй снова через <val1>",
    "max_concurrency": f"{emotes.Deny} Эта комманда не может быть использована прямо сейчас, попробуй позже...",
    "server_locked": f"{emotes.Deny} Эта команда заблокирована на этом сервере.",
    "channel_locked": f"{emotes.Deny} Используй канал для ботов, а не этот...",
    # "time_command": f"**<val3>**, сейчас:\n**<val2>** в Логове Сенко\n**<val1>** на Земле.",
    "time_command": f"**<val3>**, сейчас:\nВ Логове Сенко: **<val2>**\nМестное время: **<val1>**\nUTC: **<val4>**",
    "settings_template": "Это шаблон настроек.\nЧтобы загрузить: `<val1>settings upload`",
    "settings_template_detailed": "Это шаблон настроек.\nЧтобы загрузить: `<val1>settings upload`\nДля уровней, [USER] выводит имя пользователя, "
                                  "а [MENTION] @упоминает его.",
    "settings_current": "Текущие настройки в **<val1>**\nИспользуй `<val2>settings template` для шаблона.",
    "settings_upload_no1": f"{emotes.Deny} Это должен быть файл JSON.",
    "settings_upload_no2": f"{emotes.Deny} При получении файла произошла ошибка.",
    "settings_upload_no3": f"{emotes.Deny} Должен быть ровно один файл JSON.",
    "settings_upload_no4": f"{emotes.Deny} Ошибка при загрузке файла:\n`<val1>`",
    "settings_upload_yes": f"{emotes.Allow} Настройки были обновлены.\nСтатус базы данных: <val1>",
    "premium": "Какой ещё премиум для этого бота?",
    "eat_adde": "<val1>, Adde är inte kyckling nudlar, sluta äta honom.",
    "birthday_today": "С днём рождения, <val1>, наслаждайся своей ролью сегодня! 🎂🎉",
    "birthday_self": f"Мой день рождения **6го декабря**, спасибо, что спросил. {emotes.AlexHeart}",
    "birthday_none": "**<val1>** не сохранил его/её день рождения :(",
    "birthday_you": "У **тебя** день рождения **<val1>**",
    "birthday_other": "У **<val1>** день рождения **<val2>**",
    "birthday_already_set": "Твой день рождения уже сохранён: **<val1>**\nЧтобы изменить его, спроси владельца бота.",
    "birthday_no": "Нужно ввести дату вместе с коммандой... `[ ДД/ММ ]`",
    # "birthday_set_start": "Привет **<val1>**, введи, когда ты родился. `[ ДД/ММ ]`",
    # "birthday_no": "~~<val1>~~\n\nНу и ладно, тогда я не буду сохранять твой день рождения :(",
    "birthday_confirm": "**<val1>**, ты подтверждаешь, что твой день рождения **<val2>**?\nВведи `<val3>`, чтобы подтвердить твой выбор.\n"
                        "(ЗАМЕТКА: Чтобы изменить дату в будущем, тебе нужно будет отправить верную дату владельцу бота)",
    "birthday_no2": "~~<val1>~~\n\nНу, ты решил не отвечать...",
    "birthday_set": "Готово, теперь твой день рождения (**<val1>**) сохранён в моей базе данных 🎂",
    "eat_cake": "Kakan är en lögn.",
    "eat_noodle": "Nuudeli on liian maukas syömiseen.",
    "eat_regaus": "Hai te a muraan, ar kyda? Te vai deiken annar eitean.",
    "eat_suager": "Taa e ne, ne te a jan deamar? Paira eidea ta ten?",
    "avatar": "Аватар пользователя **<val1>**\n<val2>",
    "roles_in_server": "Роли на сервере **<val1>**",
    "user_joined_at": "**<val1>** зашёл(ла) в **<val2>**: <val3>",
    "username": "Имя пользователя",
    "nickname": "Никнейм",
    "user_id": "ID пользователя",
    "created_at": "Время создания",
    "joined_at": "Зашёл(ла) на сервер",
    "current_status": "Текущий статус",
    "current_activity": "Текущая активность",
    "no": "Нет",
    "roles": "Роли",
    "about_user": "ℹ О **<val1>**",
    "emoji_desc": "Название: <val1>\nID: <val2>\nАнимировано: <val3>\nСервер: <val4>\nВремя создания: <val5>\n[Скопировать ссылку](<val6>)",
    "only_in_senko_lair": f"{emotes.Deny} Эта комманда доступна только в Логове Сенко (Senko Lair).",
    "server_name": "Название сервера",
    "server_id": "ID сервера",
    "owner": "Владелец",
    "members": "Кол-во участников",
    "bots": "Кол-во ботов",
    "region": "Регион",
    "ban_count": "Кол-во банов",
    "access_denied": "Доступ запрещён",
    "channels": "Кол-во каналов",
    "channels2": "<val1> текстовых каналов\n<val2> категорий\n<val3> голосовых каналов",
    "about_server": "О **<val1>**",
    "server_icon": "Иконка сервера **<val1>**\n<val2>",
    "bots_in_server": "Боты в **<val1>**: ```ini\n<val2>```",
    "status_of_users": "Статус участников **<val1>**",
    "total_members": "Всего участников",
    "status": "Статус",
    "status2": "<val1> В сети: <val2> - <val3>%, из которых:\nНа телефоне: <val4> | На ПК: <val5> | В браузере: <val6>\n\n"
               "<val7> Не активны: <val8> - <val9>%, из которых:\nНа телефоне: <val10> | На ПК: <val11> | В браузере: <val12>\n\n"
               "<val13> Не беспокоить: <val14> - <val15>%, из которых:\nНа телефоне: <val16> | На ПК: <val17> | В браузере: <val18>\n\n"
               "<val19> Не в сети: <val20> - <val21>%",
    "activities": "Активность",
    "activities2": "Из <val1> человек в сети:\n<val2> Играют в игру: <val3> - <val4>%\n<val5> Пользовательский статус: <val6> - <val7>%\n"
                   "<val8> Стримят: <val9> - <val10>%\n<val11> Слушают музыку: <val12> - <val13>%\n<val14> Ничего не делают: <val15> - <val16>%",
    "default_prefixes": "Префиксы по умолчанию",
    "custom_prefixes": "Пользовательские префиксы",
    "server_prefixes": "Префиксы бота в **<val1>**",
    "bots_money": "У ботов не может быть денег, потому что они читеры. Не беспокойся, Regaus даёт мне деньги.",
    "no_money": "Похоже у <val1> вообще нет денег...",
    "balance": "У **<val1>** **<val2><val3>** в **<val4>**",
    "donate_negative": f"{emotes.Deny} Хорошая попытка, <val1>.",
    "donate_self": f"{emotes.Deny} <val1> настолько щедр, что пытается дать деньги самому себе.",
    "no_money2": f"{emotes.Deny} У тебя и так денег нет...",
    "no_money3": f"{emotes.Deny} <val1>, у тебя недостаточно денег для этого...",
    "donate_yes": f"{emotes.Allow} <val1> дал <val2><val3> <val4>. {emotes.AlexHeart}",
    "money_self": "Достаточно",
    "donated_self": "Никогда не считал",
    "more_than_you": "Больше, чем у тебя",
    "more_than_you2": "Больше, чем ты",
    "profile": "Профиль **<val1>** в **<val2>**",
    "money": "Деньги",
    "donated": "Отдано",
    "shop_empty": "Похоже, здесь ничего не продаётся...",
    "shop": "Магазин сервера **<val1>**",
    "shop_item": "<@&<val2>>: <val1><val3>\n",
    "buy_role_no": f"{emotes.Deny} <val1>, роль <val2> не продаётся...",
    "buy_role_confirm": "<val1>, ты уверен(а), что хочешь купить роль <val2> за <val3><val4>? Напиши `да`, чтобы подтвердить.",
    "buy_role_no2": "~~<val1>~~\n\nЯ принимаю отсутствие ответа как нет...",
    "buy_role_no3": f"{emotes.Deny} <val1>, у тебя уже есть роль <val2>...",
    "buy_role_no4": f"{emotes.Deny} <val1>, у тебя недостаточно денег, чтобы купить роль <val2>... (<val3>/<val4><val5>)",
    "buy_role_no5": f"{emotes.Deny} <val1>, у тебя и так нет денег...",
    "buy_role_forbidden": f"{emotes.Deny} У меня нет прав дать тебе эту роль - обратись к администраторам...",
    "buy_role_success": f"{emotes.Allow} <val1> успешно купил(а) роль <val2> за <val3><val4>.",
    "none": "Нет",
    "boosts": "Бусты сервера",
    "boosts2": "Бустов: <val1> - Уровень <val2>\nВсего бустеров: <val3>",
    "emotes": "Эмодзи",
    "emotes2": "<val3>/<val1> неанимированных\n<val2>/<val1> анимированных\n<val4> всего",
    "shard_id": "ID шарда",
    "verification_level": "Уровень проверки",
    "low": "Низкий",
    "medium": "Средний",
    "high": "Высокий",
    "extreme": "Экстремальный",
    "level_reward_failed": f"{emotes.Deny} <val1> должен получить награду за уровень, но у меня нет разрешений, чтобы это сделать.",
    "rewards_none": "Похоже, на этом сервере нет никаких наград за уровни.",
    "rewards_title": "Rewards for having no life in <val1>",
    "rewards_reward": "<val1>-й уровень: <@&<val2>>\n",
    "rank_place_unknown": "Неизвестное",
    "rank_place_num": "<val1>-е",
    "rank_level": "<val1>-й уровень",
    "rank_rank": "<val1> место",
    "rank_xp": "<val1>/<val2> опыта\nПрогресс: <val3>%",
    "rank_xp_self": "9,999,999,999,999 опыта",
    "rank_user": "Ранг пользователя **<val1>** в **<val2>**",
    "rank_self": "\nТак это же я! Зачем играть честно?",
    "nl_no_data": "У меня нет никаких данных о твоём уровне прямо сейчас...",
    "max_level": "Максимальный уровень: <val1>.",
    "xl_index_error": "Произошла ошибка при получении данных о уровне <val1>. Убедись, что он ниже максимального (<val2>).",
    "xp_level_base": "<val1>: Чтобы достичь **<val2>**-го уровня, тебе нужно **<val3> опыта**",
    "xp_level_extra": "\nОпыта до уровня: **<val1>**\nОсталось времени: примерно от **<val2> до <val3>**",
    "next_level_data": "**<val1>**: у тебя сейчас **<val2>/<val3>** опыта.\nТебе нужно ещё **<val4>**, чтобы достичь **<val5>**-го уровня. "
                       "(Прогресс: **<val6>%**).\nГоворить придётся примерно: от **<val7> до <val8>**",
    "levels_no_data": "У меня нет никаких данных об этом сервере... Странно.",
    "levels_lb": "Топ пользователей в <val1> - Отсортированно по опыту\nТвоё место: <val2>\nПоказаны с <val4>-го пo <val5>-е места\n<val3>```",
    "levels_global": "Топ пользователей глобально - Отсортированно по опыту\nТвоё место: <val1>\nПоказаны с <val3>-го пo <val4>-е места\n<val2>```",
    "experience": "Опыт",
    "level": "Уровень",
    "higher_than_yours": "Выше твоего",
    "rank_progress": "Прогресс до следующего уровня",
    "rank_progress2": "<val1>% - <val2> опыта до след. уровня",
    "xp_per_message": "Опыта за сообщение",
    "global_rank": "У **<val1>** **<val2> опыта** глобально, и он(а) занимает **<val3>** место в таблице лидеров.",
    "love_locked": f"{emotes.Deny} Представь, что ты настолько долго раздражал Regaus'а, что он для тебя заблокировал эту комманду, <val1>.",
    "bad_locked": "Иногда надо также смотреть на себя, <val1>...",
    "server_banner": "Баннер сервера **<val1>**\n<val2>",
    "server_splash": "Фон приглашения сервера **<val1>**\n<val2>",
    "server_banner_none": "У сервера **<val1>** нет баннера",
    "server_splash_none": "У сервера **<val1>** нет фона приглашения",
    "time_since": "Текущее время: **<val1>**\nУказанное время: **<val2>**\nРезультат: **<val3>**",
    "time_since_error": "Произошла ошибка:\n<val1>",
    "luas": "Данные о <val1>:\n<val2>\n<val3>",
    "current_weather": "Текущая погода",
    "temperature": "Температура",
    "pressure": "Давление",
    "humidity": "Влажность",
    "wind_speed": "Скорость ветра",
    "cloud_cover": "Облачность",
    "sunrise": "Восход",
    "sunset": "Закат",
    "weather_error": f"{emotes.Deny} не найдено данных о погоде для <val1>:\n<val2>: <val3>",
    "weather_output": "<val1> Погода в **<val2>, <val3>**\nМестное время: **<val4>**",
    # todo: translate all of this shit
    "iq": "**<val1>'s** IQ is **<val2>**",
    "hot_calc": "**<val1>** is **<val2>%** hot <val3>",
    "love_calc": "Love level between <val1> and <val2> is **<val3>**%",
    "bots_love": "Bots can't feel love towards normal users...",
    "already_taken": "<val1>, I am already taken...",
    "lc_same": "I don't think that's how it works...",
    "baby_rate": "The chance of <val1> and <val2> having a baby is **<val3>**%",
    "baby_rate_bot": "Bots weren't made to have babies...",
    "baby_rate_self": "I wasn't programmed for that, <val1>...",
    "rate": "I'd rate <val1> a **<val2>/100**",
    "message_del_error": "Message deletion failed: <val1>",
    "dm_not_found": "Could not find user with ID <val1>",
    "dm_successful": "✉️ Sent DM to **<val1>**",
    "dm_failed": "User might have blocked DMs, or be a bot account.",
    "tell_guild_diff": "The channel is not in the same server (<val2> rather than <val1>)",
    "message_send_error": "Could not send message: <val1>",
    "tell_successful": "✉️ Successfully sent message to <val1>",
    "say_successful": "✉️ Successfully sent message",
    "tell_image_none": "I need you to upload a file with the command, otherwise use <val1>tell.",
    "colour_value_len": "Value must be either 3 or 6 digits long",
    "colour_invalid": "Invalid colour: <val1>\nValue must be either `random` or a HEX value",
    "removal_message_limit": "Too many messages to search given (<val1>/2,000)",
    "removal_forbidden": "I do not have permissions to delete messages.",
    "removal_error": "Error: <val1> (try a smaller search?)",
    "removal_success": "🚮 Successfully removed <val1> message(s).",
    "removal_reactions": "Successfully removed {total_reactions} reactions.",
    "nickname_reset": "Reset **<val1>'s** nickname",
    "nickname_changed": "Changed **<val1>'s** nickname to **<val2>**",
    "unbanned": f"{emotes.Allow} Successfully unbanned <val1> (<val2>) for <val3> {emotes.BlobCatCoffee}",
    "mass_banned": f"Banned people for <val3> {emotes.BlobCatCoffee}\n{emotes.Allow} Successful: <val1>\n{emotes.Deny} Failed: <val2>",
    "ban_invalid": f"{emotes.Deny} I can't ban myself, nor my owners... {emotes.BlobCatPolice}",
    "self_harm_bad": f"{emotes.Deny} Self harm bad {emotes.BlobCatPolice}",
    "banned": f"{emotes.Allow} Successfully banned <val1> (<val2>) for <val3> {emotes.BlobCatCoffee}",
    "send_forbidden": f"{emotes.Deny} Failed to send message properly. I might be missing embed links or attach files permissions.",
    "kicked": f"{emotes.Allow} Successfully kicked <val1> (<val2>) for <val3> {emotes.BlobCatCoffee}",
    "generic": "Generic",
    "generic_info": "Developer: **<val1>**\nUptime: **<val2>**",
    "counts": "Counts",
    "counts_info": "Servers: **<val1>**\nUsers: **<val2>**\nAvg members / server: **<val3>**\nCommands: **<val4>**",
    "code_stats": "Code stats",
    "code_stats_info": "Files: **<val1>**\nLines: **<val2>**\nComments: **<val3>**\nFunctions: **<val4>**\nClasses: **<val5>**\nDocstrings: **<val6>**",
    "process": "Process",
    "process_info": "RAM: **<val1> MB**\nCPU: **<val2>%**",
    "counts2": "Server counts",
    "counts2_info": "Members: **<val1>**\nText Channels: **<val2>**\nCategories: **<val3>**\nVoice Channels: **<val4>**",
    "what_i_use": "What I use",
    "dates": "Dates",
    "dates_info": "Suager Creation: **<val1>**\nCreation of v5: **<val2>**\nLast Update: **<val3>**",
    "about_suager": "ℹ About **<val1>** | **v<val2>**",
    "source": "These are the links that Suager started with, and you should check them out if you want to make your own bot.",
    "invite_bot": "<val1>, use this link to invite me:\n<https://discordapp.com/oauth2/authorize?permissions=<val2>&client_id=<val3>&scope=bot>",
    "invite_to_sl": "<val1>, here is a link to my server:",
    "invite_to_sl_failed": "I couldn't send the link to you. To avoid problems with server rules, I try to send the link to your DMs.",
    "ping1": f"{emotes.Loading} <val1> Pong\nMessage Send: undefined\nMessage Edit: undefined\nWS Latency: <val2>ms",
    "ping2": f"{emotes.Loading} <val1> Pong\nMessage Send: <val3>ms\nMessage Edit: undefined\nWS Latency: <val2>ms",
    "ping3": f"<val1> Pong\nMessage Send: <val3>ms\nMessage Edit: <val4>ms\nWS Latency: <val2>ms",
    "quote_begin": "**<val1>** once said...",
    "quote_author": "Quote author: <val2>",
    "respects1": "**<val1>** has paid their respects <val2>",
    "respects2": "**<val1>** has paid their respects for **<val2>** <val3>",
    "roll": "**<val1>** rolled **<val2>-<val3>** and got <val4>",
    "8ball": "**Question:** <val1>\n**Answer:** <val2>",
    "beer_self": "**<val1>**: paaaarty!🎉🍺",
    "beer_me": f"{emotes.Deny} But I'm underage...",
    "beer_bot": f"{emotes.Deny} It would probably be nice to give beer to <val1>, but I don't think the bot will respond to you...",
    "beer_offer1": "**<val1>**, you got a 🍺 offer from **<val2>**",
    "beer_offer2": "\n\nReason: <val1>",
    "beer_success": "**<val1>** and **<val2>** are enjoying a lovely beer together 🍻",
    "beer_timeout": "Well, it seems that **<val1>** didn't want to have a beer with you, **<val2>**...",
    "beer_offer3": "**<val1>** got a 🍺 from **<val2>**",
    "coin_flip": "The coin landed on **<val1>**",
    "coin_flip1": "Heads",
    "coin_flip2": "Tails",
    "vibe_check1": f"{emotes.Loading} Checking **<val1>**'s vibe...",
    "vibe_check2": "**<val1>** <val2> the vibe check...",
    "vibe_check3": "failed",
    "vibe_check4": "passed",
    "vote": "A <val1> has been started by <val2>: ```fix\n<val3>```",
    "vote1": "vote",
    "vote2": "petition",
    "pickle": "**<val1>'s** pickle size is **<val2>cm**",
    "gender_already_assigned": "<val1>, your gender is already set to <val2>. You can't change it...",
    "gender_invalid": "<val1> is not a valid gender. Valid choices: `<val2>`",
    "gender_invalid2": "Gender specified does not seem to be valid...",
    "gender_set": "<val1>, your gender has been set to <val2>. Database status: <val3>",
    "gender_force_set": "<val1>'s gender is now set to <val2>. Database status: <val3>",    "image_not_created": "I could not create the image",
    "supreme_limit": "**<val1>**, the Supreme API is only limited to 500 characters...",
    "supreme_dark_light": "**<val1>**, you can't use both light and dark at the same time.",
    "pat_self": "Don't be like that...",
    "pat_suager": f"Thanks, <val1> :3 {emotes.AlexHeart} {emotes.AlexPat}",
    "inter_bot": "It's nice that you care about a bot, but I don't think <val1> will respond...",
    "pat": "<val1> got a pat from <val2>",
    "pat2": "<val1> has now received <val2> pats in this server",
    "alone": "Alone?",
    "hug_suager": f"*Hugs <val1> back* {emotes.AlexHeart}",
    "hug": "<val1> got a hug from <val2>",
    "hug2": "<val1> has now received <val2> hugs in this server",
    "cr_not_available": "Custom roles are not available in this server right now.",
    "cuddle_suager": f"*Cuddles <val1> back* {emotes.AlexHeart}",
    "cuddle": "<val1> got a cuddle from <val2>",
    "cuddle2": "<val1> has now received <val2> cuddles in this server",
    "lick_suager": "But why would you lick me, <val1>?",
    "lick_bot": "Why would you even lick a bot? It's not like <val1> would respond to you anyway.",
    "lick": "<val1> got licked by <val2>",
    "lick2": "<val1> has now been licked <val2> times in this server",
    "kiss_suager": "But why would you lick me, <val1>?",
    "kiss_bot": "Why would you even lick a bot? It's not like <val1> would respond to you anyway.",
    "kiss": "<val1> got kissed by <val2>",
    "kiss2": "<val1> has now got <val2> kisses in this server",
    "bite_suager": "But why would you bite me, <val1>?",
    "bite_bot": "Imagine biting a bot... It's not like <val1> would respond to you anyway.",
    "bite": "<val1> got bitten by <val2>",
    "bite2": "<val1> has now got bitten <val2> times in this server",
    "not_allowed": f"{emotes.Deny} You can't do that {emotes.BlobCatPolice}",
    "slap_suager": "<val1>, we are no longer friends.",
    "slap_bot": "What did <val1> even do to you?",
    "slap_bad": "Violence is not the answer, <val1>!",
    "slap": "<val1> got slapped by <val2>",
    "slap2": "<val1> has now got slapped <val2> times in this server",
    "how_are_you_gonna": f"{emotes.Deny} How are you gonna do that?",
    "smell_suager": "<val1>, we are no longer friends.",
    "smell_bot": "What did <val1> even do to you?",
    "smell": "<val1> got <val3> by <val2>",
    "smell2": "<val1> has now got <val3> <val2> times in this server",
    "smelled": "smelled",
    "sniffed": "sniffed",
    "highfive_suager": "*High fives <val1> back*",
    "highfive_bot": "How is <val1> gonna high five you back?",
    "highfive": "<val2> gave <val1> a high five",
    "highfive2": "<val1> has now got <val2> high fives in this server",
    "poke_suager": "What do you want, <val1>?",
    "poke_bot": "What are you trying to achieve by poking <val1>?",
    "poke": "<val1> got poked by <val2>",
    "poke2": "<val1> has now got poked <val2> times in this server",
    "boop_bot": "What are you trying to achieve by doing that to <val1>?",
    "boop": "<val1> got booped by <val2>",
    "boop2": "<val1> has now got booped <val2> times in this server",
    "ship_suager": "I was never programmed to feel love...",
    "ship_self": "I don't think that's how it works",
    "ship": "Nice shipping!\nShip names: **<val1>** or **<val2>**\n",
    "ship2": "\n<val1> has now been shipped <val2> times in this server!",
    "ship3": "\n<val1> has now built <val2> ships in this server!",
    "spam_stats": "Spam stats for <val1> in <val2>",
    "top_counters": "Top spammers in <val1>",
    "sleepy": "<val1> is sleepy",
    "sleepy2": "<val1> has now been sleepy <val2> times in this server",
    "cry": "<val1> is crying",
    "cry2": "<val1> has now cried <val2> times in this server",
    "blush": "<val1> blushes",
    "blush2": "<val1> has now blushed <val2> times in this server",
    "smile": "<val1> smiles",
    "smile2": "<val1> has now smiled <val2> times in this server",
    "bang_suager": "Nope, find someone else.",
    "bang": "bang",
    "fuck": "fuck",
    "bang_out": f"{emotes.Scary} {emotes.NotLikeThis} <val1> is now <val4>ing <val2>...\n<val2> has now got <val4>ed <val3> times in this server!",
    "bean_not_allowed": f"{emotes.Deny} You are not allowed to do that {emotes.BlobCatPolice}",
    "bean_suager": f"{emotes.Deny} You can't bean me",
    "bean_owner": f"{emotes.Deny} Imagine beaning the owner, lol",
    "bean": f"{emotes.Allow} <val1> has been dismissed from <val2>.\n<val1> has now been beaned <val3> times in this server",
    "bean2": f"{emotes.Deny} <val1> has been dismissed from <val2>.",
    "bad_suager": "If you think I'm bad, why am I still in this server?",
    "eat_allowed": "You can only eat: cookie, carrot, fruit, lemon",
    "cookie_singular": "cookie",
    "cookie_plural": "cookies",
    "carrot_singular": "carrot",
    "carrot_plural": "carrots",
    "fruit_plural": "fruits",
    "fruit_singular": "fruit",
    "lemon_singular": "lemon",
    "lemon_plural": "lemons",
    "eat_none": f"{emotes.Deny} You don't have any <val1> right now...",
    "eat_none_left": f"{emotes.Deny} You don't have any <val1> left...",
    "eat": "<val1>, you just ate a <val2>. You have <val3> left.",
    "no_greedy": "Don't be greedy, <val1>!",
    "give_food": "<val2> just got a <val3> from <val1>",
    "food_counter": "<val1> now has <val2> <val3> in this server",
}
